services:
  mysql:
    image: mysql:8.0
    container_name: word-english-share-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - /Users/kimkyungho/dev/mysql:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--bind-address=0.0.0.0"
    networks:
      - docker_network

  application:
    ports:
      - "8080:8080"
    container_name: word-english-share
    image: kimkyungho/word-english-share
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - /home/ubuntu/logs:/app/logs
    networks:
      - docker_network

networks:
  docker_network: