services:
  application:
    ports:
      - "8080:8080"
    container_name: word-english-share
    image: kimkyungho/word-english-share
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ubuntu/logs:/app/logs
    networks:
      - docker_network

networks:
  docker_network: